
from random import random
import string


f = open('wordList.txt')
words = f.read().lower().splitlines()
lettersIn = []
lettersNotIn = []
lettersInPos = []
# This is generated from the wordlist.txt and is generated by `countMostCommonLetters.py`
commonLetters = {'w': 505, 'h': 814, 'i': 1592, 'c': 964, 't': 1585, 'e': 3009, 'r': 1910, 'a': 2348, 'b': 715, 'o': 1915, 'u': 1089, 'l': 1586,
                 'd': 1181, 's': 3033, 'f': 561, 'g': 679, 'n': 1285, 'k': 596, 'y': 886, 'p': 955, 'v': 318, 'm': 843, 'q': 53, 'j': 89, 'x': 139, 'z': 135}


def getHeuristicNumber(word: string):
    # Sort words based on how common there unique letters are
    letters = list(dict.fromkeys([letter for letter in word]))
    return sum([commonLetters[letter] for letter in letters])


# Filter letters that only have the right letters with the right pos


def filterLettersInPos(word: string):
    if len(lettersInPos) == 0:
        return True
    returnVal = True
    for (pos, letter) in lettersInPos:
        if word[pos] != letter:
            returnVal = False
    return returnVal

# Filter out letters that are not in the word


def filterLettersNotIn(word: string):
    if len(lettersNotIn) == 0:
        return True
    for letter in word:
        if letter in lettersNotIn:
            return False
    return True

# Filter out letters that are in the word


def filterLeters(word: string):
    if len(lettersIn) == 0:
        return True
    wordArr = [let for let in word]
    for letter in lettersIn:
        if not (letter in wordArr):
            return False

    return True


def pickWord():
    filterTwice = list(filter(
        filterLettersNotIn, words))
    filterOnce = list(filter(
        filterLeters, filterTwice))

    newWords = list(filter(filterLettersInPos, filterOnce))

    if len(newWords) == 0:
        print("ERROR: no more words")
        exit(1)

    pickArr = sorted(newWords, key=getHeuristicNumber, reverse=True)
    return pickArr[0]


done = False
while not done:
    word = pickWord()
    print(word)
    print('Enter letters that are not in the word (seperated by comma)')
    for x in input().split(','):
        if x:
            lettersNotIn.append(x.strip().lower())

    print('Enter letters that are in the word (seperated by comma)')
    for x in input().split(','):
        if x:
            lettersIn.append(x.strip().lower())
    print('Enter letters and position that are in the word (seperated by comma)')
    for x in input().split(','):
        if x:
            ents = x.split("|")
            lettersInPos.append((int(ents[0]), ents[1].strip().lower()))
    print('Are you done?')
    done = input() == 'yes'


f.close()
